### ISSUE TITLE
Gauge.VisualStudio.Templates should be available for 2019

### ISSUE THREAD

**Issue by ngbrown** [getgauge-contrib/gauge-visualstudio-templates#2]
It is listed in the marketplace as "Works with Visual Studio 2015, 2017".  When attempting to install, does not give the option to install into Visual Studio 2019, even though it is installed.

**Comment by sriv** [comment]
Gauge-Visualstudio does not work with VS 2019 (yet). And we didn't see much value in enabling templates alone for VS2019.
